### ISSUE TITLE
在linux中移植出现的问题

### ISSUE THREAD

**Issue by jimmy-sketch** [jimmy-sketch/chen_cppcguilib#13]
![image](https://github.com/user-attachments/assets/162fc62f-2ca1-4111-8df0-a7b5c04d360e)
![image](https://github.com/user-attachments/assets/e1dff6eb-d3a6-4eb3-b68b-56aaf869eaa7)
从目前来看，sandbox中的conio库是无法在linux g++ 11.4.0下使用的，需要替换为curses库。同时，还有万恶的`fopen_s`。其次，在g++下，似乎链接过程出了一点问题，似乎跟名称修饰有一点关系。

**Comment by hnsk0808** [comment]
我新增了一个main_linux，发布在pr，但没有linux环境测试不了正确性。
你看看能不能用，不好用的话你补充一下

另外，你有没有把util/string.cpp编译到库里面？

**Comment by jimmy-sketch** [comment]
额，我好像确实是忘记编译string了=（
过一会我会在wsl和zsh/bash/sh下面测试一下，如果可以的话就合并了。
