### ISSUE TITLE
在linux(zsh)下当sandbox执行完毕后光标被隐藏

### ISSUE THREAD

**Issue by jimmy-sketch** [jimmy-sketch/chen_cppcguilib#20]
如图所示：

https://github.com/user-attachments/assets/6a617db0-389e-4a45-ad40-8ccf4934ce44

光标被异常隐藏了
版本：Ubuntu(wsl) 22.04.4LTS+zsh 5.8.1
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by hnsk0808** [comment]
因为程序结束后光标还是隐藏的，在main的最前面加入下面的代码解决问题。
```C++
#include <csignal>
signal(SIGINT, [](int s) {
    printf("\x1B[?25h");
    exit(0);
});
```
当程序被关闭时，printf("\x1B[?25h");显示光标，然后用exit(0);退出程序。
这段代码同时适用于windows和linux。
